AuthType Basic
AuthName "Restricted Area"
AuthUserFile /path/to/.htpasswd
Require valid-user

RewriteEngine On
RewriteBase /b2l/

# APIを除外
RewriteCond %{REQUEST_URI} ^/b2l/api/ [NC]
RewriteRule .* - [L]

# Scorerを除外
RewriteCond %{REQUEST_URI} ^/b2l/scorer/ [NC]
RewriteRule .* - [L]

AddDefaultCharset UTF-8

